
BLENDER="C:\Program Files\Blender Foundation\Blender 4.2\blender.exe"
DIST=../dist

all : \
    $(DIST)/guppy.pnct \
    $(DIST)/guppy.scene \

$(DIST)/guppy.scene : guppy.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "guppy.blend:Main" "$(DIST)/guppy.scene"

$(DIST)/guppy.pnct : guppy.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "guppy.blend:Main" "$(DIST)/guppy.pnct" 
